### ISSUE TITLE
deploy_local.sh no longer works out of the box

### ISSUE THREAD

**Issue by KalmanMeth** [SODALITE-EU/iac-platform-stack#8]
When running deploy_local.sh, the various items are installed, and deployment begins, but fails at a certain point.

```
TLS certificate does not exist. Generating...
  Deploying sodalite-vm_0
  Deploying docker-host_0
    Executing create on docker-host_0
  Deploying docker-network_0
    Executing create on docker-network_0
  Deploying docker-public-registry_0
    Executing create on docker-public-registry_0
  Deploying docker-registry-certificate_0
    Executing create on docker-registry-certificate_0
  Deploying xopera-openstack-keys_0
    Executing create on xopera-openstack-keys_0
.........
                {
                    "hosts": {
                        "opera": {
                            "_ansible_no_log": false,
                            "action": "authorized_key",
                            "failed": true,
                            "msg": "The task includes an option with an undefined variable. The error was: 'ansible_user' is undefined\n\nThe error appears to be in '/tmp/tmpl8204nvy/create.yml': line 29, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n          register: key\n        - authorized_key:\n          ^ here\n"
                        }
                    },
.......
------------
============
Traceback (most recent call last):
  File "/home/meth/sodalite/iac-platform-stack/.venv/bin/opera", line 11, in <module>
    sys.exit(main())
  File "/home/meth/sodalite/iac-platform-stack/.venv/lib/python3.6/site-packages/opera/cli.py", line 41, in main
    return args.func(args)
  File "/home/meth/sodalite/iac-platform-stack/.venv/lib/python3.6/site-packages/opera/commands/deploy.py", line 43, in deploy
    topology.deploy()
  File "/home/meth/sodalite/iac-platform-stack/.venv/lib/python3.6/site-packages/opera/instance/topology.py", line 25, in deploy
    node.deploy()
  File "/home/meth/sodalite/iac-platform-stack/.venv/lib/python3.6/site-packages/opera/instance/node.py", line 61, in deploy
    self.run_operation("HOST", "Standard", "create")
  File "/home/meth/sodalite/iac-platform-stack/.venv/lib/python3.6/site-packages/opera/instance/base.py", line 70, in run_operation
    raise OperationError("Failed")
opera.error.OperationError: Failed
```

**Comment by kmlTE** [comment]
There is another issue with the deployment script, which is caused by incompatibility of apt and pip versions of ansible:
```
The following NEW packages will be installed:
  ansible
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 5.794 kB of archives.
After this operation, 58,0 MB of additional disk space will be used.
Get:1 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 ansible all 2.9.6+dfsg-1 [5.794 kB]
Fetched 5.794 kB in 1s (9.048 kB/s)  
Selecting previously unselected package ansible.
(Reading database ... 222931 files and directories currently installed.)
Preparing to unpack .../ansible_2.9.6+dfsg-1_all.deb ...
Unpacking ansible (2.9.6+dfsg-1) ...
Setting up ansible (2.9.6+dfsg-1) ...
Processing triggers for man-db (2.9.1-1) ...
libdvd-pkg: Checking orig.tar integrity...
/usr/src/libdvd-pkg/libdvdcss_1.4.2.orig.tar.bz2: OK
libdvd-pkg: `apt-get check` failed, you may have broken packages. Aborting...

Creating new venv

Installing xOpera
Collecting opera==0.6.2
  Using cached opera-0.6.2-py3-none-any.whl (75 kB)
Collecting ansible>=2.8
  Using cached ansible-2.10.4.tar.gz (28.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/kml/sodalite/github-repo/iac-platform-stack/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iid8bc_m/ansible/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iid8bc_m/ansible/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-iid8bc_m/ansible/pip-egg-info
         cwd: /tmp/pip-install-iid8bc_m/ansible/
    Complete output (31 lines):
    
    
                ### ERROR ###
    
                Upgrading directly from ansible-2.9 or less to ansible-2.10 or greater with pip is
                known to cause problems.  Please uninstall the old version found at:
    
                /usr/lib/python3/dist-packages/ansible/__init__.py
    
                and install the new version:
    
                    pip uninstall ansible
                    pip install ansible
    
                If you have a broken installation, perhaps because ansible-base was installed before
                ansible was upgraded, try this to resolve it:
    
                    pip install --force-reinstall ansible ansible-base
    
                If ansible is installed in a different location than you will be installing it now
                (for example, if the old version is installed by a system package manager to
                /usr/lib/python3.8/site-packages/ansible but you are installing the new version into
                ~/.local/lib/python3.8/site-packages/ansible with `pip install --user ansible`)
                or you want to install anyways and cleanup any breakage afterwards, then you may set
                the ANSIBLE_SKIP_CONFLICT_CHECK environment variable to ignore this check:
    
                    ANSIBLE_SKIP_CONFLICT_CHECK=1 pip install --user ansible
    
                ### END ERROR ###
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Since opera does install ansible, [the line 81 of the script](https://github.com/SODALITE-EU/iac-platform-stack/blob/master/deploy_local.sh#L81) can be deleted.

**Comment by mihaTrajbaric** [comment]
It must definitely be deleted. I also added code to remove the previous installation of ansible < 2.10 and replace it with 2.10
